# Домашнее задание №1. Pandas. numpy. Обработка данных

## Ф.И.О: Чайкин Владимир

Домашнее задание состоит из **2**-х частей: 
- **Первая часть** посвящена эффективной реализации функций подсчета расстояния с использованием библиотеки _numpy_.
- **Вторая часть** предполагает заполнение предложенного блокнота.

### Часть 0.
- Вписать Ваши ФИО в предложенное поле.


### Часть 1. (5 баллов)
- реализуйте функции для вычисления расстояния из модуля ``tasks`` с использованием _numpy_
- запрещается использовать циклы и конструкцию list comprehension
- запрещается использовать сторонние библиотеки (за исключением _numpy_)
- для проверки можете использовать приложенные unit-тесты
   - чтобы запустить их в консоли выполните:
      ``$ python3 -m unittest``

### Часть 2. (15 баллов)
- заполните предложенный блокнот кодом и ответами на вопросы, где это требуется

----------------------------------------

**На проверку требуется отправить zip архив, который будет содержать следующие файлы:**
 - модуль ``tasks.py`` с реализованными функциями
 - заполненный блокнот в формате ``.ipynb``
 - заполненный блокнот в формате ``.html`` **(в jupyter: File -> Save and Export Notebook As -> HTML -> ...)**
 - файл ``answer.csv``, который получится в результате работы над блокнотом

### Часть 2. (15 points)

----------------------------

#### __1__. (2 points)

__1.1__. Импортируйте все необходимые библиотеки.

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 100)
pd.set_option('display.precision', 3)

import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

__1.2__. Загрузите файл `train.csv` и сохраните его в переменную `df`. Выведите первые 10 строчек таблицы.

In [56]:
df = pd.read_csv('train.csv')
df.head(10)

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum
0,01/10/2017,0,5200,NaN,810,21OCT17:00:00:00,5023.0,POS,0,0.0
1,01/10/2017,0,6011,NaN,810,12OCT17:12:24:07,20000.0,DEPOSIT,0,0.0
2,01/12/2017,0,5921,NaN,810,05DEC17:00:00:00,767.0,POS,0,0.0
3,01/10/2017,0,5411,NaN,810,21OCT17:00:00:00,2031.0,POS,0,0.0
4,01/10/2017,0,6012,NaN,810,24OCT17:13:14:24,36562.0,C2C_OUT,0,0.0
5,01/10/2017,1,5814,NaN,810,16OCT17:00:00:00,380.0,POS,0,0.0
6,01/10/2017,1,5814,NaN,810,10OCT17:00:00:00,378.0,POS,0,0.0
7,01/10/2017,1,5814,NaN,810,16OCT17:00:00:00,199.0,POS,0,0.0
8,01/10/2017,1,5814,NaN,810,11OCT17:00:00:00,400.0,POS,0,0.0
9,01/07/2017,1,5411,NaN,810,26JUL17:00:00:00,598.0,POS,0,0.0

In [57]:
np.random.seed(9564)
index = np.random.choice(len(df), replace=False, size=1000)

__1.3__.1. Выведите размер получившейся таблицы.

In [58]:
table_size = df.shape
print(f"Размер таблицы: {table_size}")

Размер таблицы: (490513, 10)

__1.3__.2. Выведите статистики (среднее, дисперсию, кванти́ли, количество значений и т.п.) по каждому из столбцов. Воспользуйтесь специальным методом у `df`.

In [59]:
df.describe(include='all')

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum
count,490513,490513.000,490513.000,487603,490513.000,490513,4.905e+05,490513,490513.000,4.905e+05
unique,19,NaN,NaN,5,NaN,58113,NaN,10,NaN,NaN
top,01/07/2017,NaN,NaN,type1,NaN,23JUN17:00:00:00,NaN,POS,NaN,NaN
freq,55757,NaN,NaN,299247,NaN,1971,NaN,416425,NaN,NaN
mean,NaN,4802.127,5699.784,NaN,810.602,NaN,5.724e+03,NaN,0.653,1.627e+05
std,NaN,2986.493,662.933,NaN,38.223,NaN,7.704e+04,NaN,0.476,1.474e+06
min,NaN,0.000,742.000,NaN,32.000,NaN,4.000e-02,NaN,0.000,0.000e+00
25%,NaN,2193.000,5411.000,NaN,810.000,NaN,2.240e+02,NaN,0.000,0.000e+00
50%,NaN,4576.000,5661.000,NaN,810.000,NaN,6.240e+02,NaN,1.000,2.491e+04
75%,NaN,7390.000,5941.000,NaN,810.000,NaN,2.176e+03,NaN,1.000,1.516e+05
max,NaN,10215.000,9405.000,NaN,986.000,NaN,3.584e+07,NaN,1.000,4.607e+07

Опиание столбцов:
* PERIOD – месяц транзакции;
* cl_id – id клиента;
* MCC – код категории продавца;
* channel_type – канал привлечения клиента;
* currency – валюта;
* TRDATETIME – дата/время транзакции;
* amount – сумма транзакции;
* trx_category – вид транзакции.

Виды транзакций:
* POS – оплата через POS терминал;
* C2C_IN – перевод на карту (входящий платёж);
* C2C_OUT – перевод на карту (исходящий платёж);
* DEPOSIT – пополнение карты в банкомате;
* WD_ATM_PARTNER – снятие наличных в банкоматах партнерах банка *UNKNOWN*;
* WD_ATM_ROS – снятие наличных в банкоматах банка *UNKNOWN*;
* WD_ATM_OTHER – снятия в других банкоматах;
* BACK_TRX – возврат средств при возврате покупки;
* CAT – операции в банкоматах;
* CASH_ADV – снятие карты в кассе банка.

__1.4__. Какие столбцы имеют пропущенные значения? Сколько пропущенных значений?

In [60]:
print("Пропущенные значения по столбцам:")
print(df.describe(include='all').isnull().sum())

Пропущенные значения по столбцам:
PERIOD          7
cl_id           3
MCC             3
channel_type    7
currency        3
TRDATETIME      7
amount          3
trx_category    7
target_flag     3
target_sum      3
dtype: int64

__1.5__. Какие уникальные значения существуют у столбца `currency`?

In [61]:
print("Уникальные значения в столбце currency:")
print(df['currency'].unique())

Уникальные значения в столбце currency:
[810 978 504 704 981 985 840 949  51 826 214 764 203 702 360 756 933 975
  36 191 784 980 124 398 376 944 352 417 156 752 392 484 634 188 643 348
 356 458 986 498 578 208 344  32 410 788 480 604 941 144 946 710 690  44
 170 901 608 554 462]

__1.6__. Заполните пропуски в столбце `channel_type` значением `type0`. Результат должен сохраниться в переменной `df`.

In [62]:
df['channel_type'] = df['channel_type'].fillna('type0')

In [63]:
df.head()

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum
0,01/10/2017,0,5200,type0,810,21OCT17:00:00:00,5023.0,POS,0,0.0
1,01/10/2017,0,6011,type0,810,12OCT17:12:24:07,20000.0,DEPOSIT,0,0.0
2,01/12/2017,0,5921,type0,810,05DEC17:00:00:00,767.0,POS,0,0.0
3,01/10/2017,0,5411,type0,810,21OCT17:00:00:00,2031.0,POS,0,0.0
4,01/10/2017,0,6012,type0,810,24OCT17:13:14:24,36562.0,C2C_OUT,0,0.0

__1.7__. Посчитайте, сколько записей приходится на каждое уникальное значение столбца `channel_type`.

In [64]:
print(df['channel_type'].value_counts())

channel_type
type1    299247
type2    175013
type5      5587
type4      4476
type3      3280
type0      2910
Name: count, dtype: int64

__1.8__. Найдите топ-3 `MCC` категорий с наибольшим объемом трат (поле `amount`).

In [65]:
print(df.groupby('MCC')['amount'].sum().sort_values(ascending=False).head(3))

MCC
6011    1.494e+09
6012    1.849e+08
5411    1.347e+08
Name: amount, dtype: float64

----------------------------------

#### __2__. (1 point)

__2.1__. Сделайте значения в столбцах `channel_type` и `trx_category` категориальными.

In [66]:
df['channel_type'] = df['channel_type'].astype('category')
df['trx_category'] = df['trx_category'].astype('category')

__2.2__. Сделайте столбец `trx_category_mul`, который показывает увеличение (значение в столбце равно +1) и уменьшение средств (значение в столбце равно -1) на счете клиента банка. Операции, которые увеличивают количество средств на счете:
`C2C_IN`, `DEPOSIT`, `BACK_TRX`. Считайте, что остальные операции уменьшают количество средств на счете.

In [67]:
increase_categories = ['C2C_IN', 'DEPOSIT', 'BACK_TRX']
df['trx_category_mul'] = df['trx_category'].apply(
    lambda x: 1 if x in increase_categories else -1
)

In [68]:
df.loc[:, ['trx_category_mul', 'trx_category']].head()

   trx_category_mul trx_category
0                -1          POS
1                 1      DEPOSIT
2                -1          POS
3                -1          POS
4                -1      C2C_OUT

-------------------------------------------------

#### __3__. (1 point)

__3.0__. Приведем столбец `TRDATETIME` к типу даты.

In [69]:
from datetime import datetime

df["TRDATETIME"] = pd.to_datetime(df["TRDATETIME"], format='%d%b%y:%H:%M:%S')

Извлеките из столбца `TRDATETIME` следующие признаки:
* `mday` – день (с начала месяца);
* `ymonth` – месяц;
* `year` – год;
* `wday` – день недели;
* `is_weekend` – является ли день выходным днем.

Извлеченные признаки запишите в таблицу `df_time`.

In [70]:
df_time = pd.DataFrame()

df_time['mday'] = df['TRDATETIME'].dt.day      
df_time['ymonth'] = df['TRDATETIME'].dt.month 
df_time['year'] = df['TRDATETIME'].dt.year        
df_time['wday'] = df['TRDATETIME'].dt.dayofweek

df_time['is_weekend'] = (df_time['wday'] >= 5).astype(int)

In [71]:
df_time.head()

   mday  ymonth  year  wday  is_weekend
0    21      10  2017     5           1
1    12      10  2017     3           0
2     5      12  2017     1           0
3    21      10  2017     5           1
4    24      10  2017     1           0

__3.1__. Объедините таблицы `df` и `df_time` и сохраните результат в `df`. При объединении используйте аргумент `sort=False`, если он имеется.

In [72]:
df = pd.concat([df, df_time], axis=1, sort=False)

In [73]:
df.head()

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum,trx_category_mul,mday,ymonth,year,wday,is_weekend
0,01/10/2017,0,5200,type0,810,2017-10-21 00:00:00,5023.0,POS,0,0.0,-1,21,10,2017,5,1
1,01/10/2017,0,6011,type0,810,2017-10-12 12:24:07,20000.0,DEPOSIT,0,0.0,1,12,10,2017,3,0
2,01/12/2017,0,5921,type0,810,2017-12-05 00:00:00,767.0,POS,0,0.0,-1,5,12,2017,1,0
3,01/10/2017,0,5411,type0,810,2017-10-21 00:00:00,2031.0,POS,0,0.0,-1,21,10,2017,5,1
4,01/10/2017,0,6012,type0,810,2017-10-24 13:14:24,36562.0,C2C_OUT,0,0.0,-1,24,10,2017,1,0

--------------------------

#### __4__. (1 point)

__4.1__. Загрузите таблицу `mcc_codes_ru.csv` и сохраните в переменную `df_mcc`. Выведите первые 5 строчек таблицы.

In [74]:
df_mcc = pd.read_csv('mcc_codes_ru.csv')

print("Первые 5 строк таблицы mcc_codes_ru.csv:")
df_mcc.head(5)

Первые 5 строк таблицы mcc_codes_ru.csv:

,MCC,Название,Группа,Обновлено
0,742,Ветеринарные услуги,Контрактные услуги,31.01.18
1,763,Сельскохозяйственные кооперативы,Контрактные услуги,31.01.18
2,780,Услуги садоводства и ландшафтного дизайна,Контрактные услуги,31.01.18
3,1520,Генеральные подрядчики – жилое и коммерческое ...,Контрактные услуги,31.01.18
4,1711,"Генеральные подрядчики по вентиляции, теплосна...",Контрактные услуги,31.01.18

__4.2__. Переименуйте столбцы в `df_mcc` следующим образом:
* `MCC` -> `MCC`;
* `Название` -> `mcc_name`;
* `Группа` -> `mcc_group`;
* `Обновлено` -> `updated`.

Результат сохраните в `df_mcc`.

In [75]:
df_mcc = df_mcc.rename(columns={
    'MCC': 'MCC',
    'Название': 'mcc_name', 
    'Группа': 'mcc_group',
    'Обновлено': 'updated'
})

In [76]:
df_mcc.head()

,MCC,mcc_name,mcc_group,updated
0,742,Ветеринарные услуги,Контрактные услуги,31.01.18
1,763,Сельскохозяйственные кооперативы,Контрактные услуги,31.01.18
2,780,Услуги садоводства и ландшафтного дизайна,Контрактные услуги,31.01.18
3,1520,Генеральные подрядчики – жилое и коммерческое ...,Контрактные услуги,31.01.18
4,1711,"Генеральные подрядчики по вентиляции, теплосна...",Контрактные услуги,31.01.18

__4.3__. Удалите столбец `updated` из `df_mcc`, результат сохраните в `df_mcc`.

In [77]:
df_mcc = df_mcc.drop('updated', axis=1)

In [78]:
df_mcc.head()

    MCC                                           mcc_name           mcc_group
0   742                                Ветеринарные услуги  Контрактные услуги
1   763                   Сельскохозяйственные кооперативы  Контрактные услуги
2   780          Услуги садоводства и ландшафтного дизайна  Контрактные услуги
3  1520  Генеральные подрядчики – жилое и коммерческое ...  Контрактные услуги
4  1711  Генеральные подрядчики по вентиляции, теплосна...  Контрактные услуги

__4.4__. Закодируйте столбец `mcc_group` с помощью label-кодирования.

In [82]:
unique_values = df_mcc['mcc_group'].unique()

label_mapping = {value: idx for idx, value in enumerate(unique_values)}

df_mcc['mcc_group'] = df_mcc['mcc_group'].map(label_mapping)

In [83]:
df_mcc.head()

    MCC                                           mcc_name  mcc_group
0   742                                Ветеринарные услуги          0
1   763                   Сельскохозяйственные кооперативы          0
2   780          Услуги садоводства и ландшафтного дизайна          0
3  1520  Генеральные подрядчики – жилое и коммерческое ...          0
4  1711  Генеральные подрядчики по вентиляции, теплосна...          0

--------------------------------------
#### __5__. (2 points)

__5.1__. Присоедините к таблице `df` столбец `mcc_group`. Результат сохраните в `df`.

**Какой тип JOIN-а подойдет лучше всего для этой задачи?**

$\textcolor{red}{Ваш \ ответ:}$ Left join, так как нам нужно сохранить все строки основной таблицы

In [84]:
df = df.merge(df_mcc[['MCC', 'mcc_group']], on='MCC', how='left')

In [85]:
df.iloc[index].head()

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum,trx_category_mul,mday,ymonth,year,wday,is_weekend,mcc_group
51305,01/06/2017,913,7230,type2,810,2017-06-14,2100.0,POS,1,449004.29,-1,14,6,2017,2,0,14.0
226863,01/07/2017,4183,5499,type1,810,2017-07-20,140.0,POS,1,132726.55,-1,20,7,2017,3,0,9.0
124479,01/11/2017,2253,5735,type2,810,2017-11-28,397.0,POS,1,59.00,-1,28,11,2017,1,0,12.0
11132,01/08/2017,225,5411,type4,810,2017-08-07,44.9,POS,1,466235.45,-1,7,8,2017,0,0,9.0
473017,01/03/2017,9869,5812,type1,810,2017-03-30,350.0,POS,0,0.00,-1,30,3,2017,3,0,12.0

----------------------------------------

#### __6__. (2 points) 
Выведите сумму, среднее и среднеквадратичное отклонение трат `amount` по каждой из категорий `trx_category` в рамках канала привлечения `channel_type`.

In [88]:
stats_by_channel_category = df.groupby(['channel_type', 'trx_category'])['amount'].agg([
    'sum',    
    'mean',   
    'std',        
    'count'   
])

print(stats_by_channel_category)

                                   sum       mean         std   count
channel_type trx_category
type0        BACK_TRX        3.319e+04   8297.250    4781.941       4
             C2C_IN          9.402e+05  22386.441   29685.787      42
             C2C_OUT         2.033e+05   4148.317    6442.629      49
             CASH_ADV        0.000e+00        NaN         NaN       0
             CAT             8.404e+04   9338.331    6850.960       9
             DEPOSIT         2.608e+06  18363.380   19525.900     142
             POS             4.414e+06   1776.817    6213.823    2484
             WD_ATM_OTHER    1.112e+06  52933.333  225027.019      21
             WD_ATM_PARTNER  2.285e+05   6528.571   16563.382      35
             WD_ATM_ROS      1.796e+06  14487.097   31677.891     124
type1        BACK_TRX        2.055e+07  10979.486   55181.355    1872
             C2C_IN          7.037e+07  13497.176   21455.762    5214
             C2C_OUT         4.609e+07  16562.824   25755.712    2783
             CASH_ADV        6.548e+05  25185.410   59272.348      26
             CAT             7.320e+06  16087.923   74133.156     455
             DEPOSIT         3.691e+08  21132.086   27362.956   17464
             POS             6.323e+08   2472.164   70228.802  255784
             WD_ATM_OTHER    3.840e+07  19145.017  177771.182    2006
             WD_ATM_PARTNER  2.264e+08  47388.371   71325.839    4777
             WD_ATM_ROS      3.837e+08  43278.339   55730.322    8866
type2        BACK_TRX        3.422e+06   4700.521   12835.219     728
             C2C_IN          2.698e+07  14020.438   25895.815    1924
             C2C_OUT         3.938e+07  15804.485   25665.438    2492
             CASH_ADV        2.580e+05  32250.535   52204.208       8
             CAT             1.045e+07  16335.570   81574.126     640
             DEPOSIT         8.448e+07  30597.081   38968.512    2761
             POS             3.464e+08   2357.908   98286.422  146919
             WD_ATM_OTHER    3.421e+07   6909.320   32450.823    4952
             WD_ATM_PARTNER  9.920e+07  20572.605   33867.718    4822
             WD_ATM_ROS      2.699e+08  27632.246   43508.296    9767
type3        BACK_TRX        3.222e+05  20139.201   35475.888      16
             C2C_IN          8.701e+04  10876.250   12332.637       8
             C2C_OUT         3.543e+04   5061.857    7569.332       7
             CASH_ADV        0.000e+00        NaN         NaN       0
             CAT             2.408e+06  63373.589  122651.324      38
             DEPOSIT         4.344e+06  23227.273   23103.532     187
             POS             7.837e+06   2755.509   10612.661    2844
             WD_ATM_OTHER    2.460e+05   9840.080   19904.776      25
             WD_ATM_PARTNER  2.386e+06  28401.190   36133.539      84
             WD_ATM_ROS      2.274e+06  32023.944   44980.924      71
type4        BACK_TRX        2.259e+05   7531.287   28910.156      30
             C2C_IN          8.869e+05  15291.915   12320.494      58
             C2C_OUT         1.846e+06  20977.273   26067.515      88
             CASH_ADV        0.000e+00        NaN         NaN       0
             CAT             6.288e+04  12575.312   17346.537       5
             DEPOSIT         1.190e+07  39282.607   42093.366     303
             POS             1.169e+07   3138.924   23228.570    3725
             WD_ATM_OTHER    1.829e+05   4572.299    4388.775      40
             WD_ATM_PARTNER  3.161e+06  38085.542   56640.958      83
             WD_ATM_ROS      7.700e+06  53475.694   66417.188     144
type5        BACK_TRX        6.224e+04   1682.229    2331.338      37
             C2C_IN          6.334e+05  10556.333   11777.934      60
             C2C_OUT         5.111e+05  13812.508   20574.017      37
             CASH_ADV        0.000e+00        NaN         NaN       0
             CAT             2.273e+06  45459.432   30754.892      50
             DEPOSIT         1.036e+07  28865.955   33653.585     359
             POS             1.036e+07   2218.382   20558.593    4669
             WD_ATM_OTHER    6.203e+05   6461.146   16581.908      96
             WD_ATM_PARTNER  1.367e+06   9300.000   19181.198     147
             WD_ATM_ROS      2.724e+06  20636.364   32177.241     132

/var/folders/71/l9x053c57wq5135x6_syytm80000gn/T/ipykernel_12349/2728175680.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  stats_by_channel_category = df.groupby(['channel_type', 'trx_category'])['amount'].agg([

---------------------------------

#### __7__. (2 points) 

Выведите топ-5 клиентов, с наибольшим оборотом по `С2С` транзакциям. Под оборотом подразумевается полный объем полученных и переведенных средств без учета знака (т.е. не имеет значения получал ли клиент средства на свой счет, или переводил их на другой счет).

In [89]:
c2c_transactions = df[df['trx_category'].isin(['C2C_IN', 'C2C_OUT'])]

top_clients_c2c = c2c_transactions.groupby('cl_id')['amount'].apply(
    lambda x: x.abs().sum()
).sort_values(ascending=False).head(5)

print(top_clients_c2c)

cl_id
4445    3.237e+06
1408    1.896e+06
4211    1.714e+06
5373    1.262e+06
4340    1.259e+06
Name: amount, dtype: float64

-------------------------------------------

#### __8__. (2 points) 

__8.1.__ Прологарифмируйте сумму трат `amount`, а результат сохраните в столбец `amount_log`. Как нужно логарифмировать, чтобы не было проблем при `amount == 0`?

In [90]:
df['amount_log'] = np.log(df['amount'] + 1)

__8.2__. Выполните onehot-кодирование для столбцов `channel_type` и `trx_category`. Полученные столбцы присоедините к таблице `df`, результат сохраните в переменную `df`.

In [91]:
channel_type_dummies = pd.get_dummies(df['channel_type'], prefix='channel')
trx_category_dummies = pd.get_dummies(df['trx_category'], prefix='trx')

df = pd.concat([df, channel_type_dummies, trx_category_dummies], axis=1)

In [92]:
df.iloc[index].head()

,PERIOD,cl_id,MCC,channel_type,currency,TRDATETIME,amount,trx_category,target_flag,target_sum,trx_category_mul,mday,ymonth,year,wday,is_weekend,mcc_group,amount_log,channel_type0,channel_type1,channel_type2,channel_type3,channel_type4,channel_type5,trx_BACK_TRX,trx_C2C_IN,trx_C2C_OUT,trx_CASH_ADV,trx_CAT,trx_DEPOSIT,trx_POS,trx_WD_ATM_OTHER,trx_WD_ATM_PARTNER,trx_WD_ATM_ROS
51305,01/06/2017,913,7230,type2,810,2017-06-14,2100.0,POS,1,449004.29,-1,14,6,2017,2,0,14.0,7.650,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
226863,01/07/2017,4183,5499,type1,810,2017-07-20,140.0,POS,1,132726.55,-1,20,7,2017,3,0,9.0,4.949,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False
124479,01/11/2017,2253,5735,type2,810,2017-11-28,397.0,POS,1,59.00,-1,28,11,2017,1,0,12.0,5.986,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False
11132,01/08/2017,225,5411,type4,810,2017-08-07,44.9,POS,1,466235.45,-1,7,8,2017,0,0,9.0,3.826,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
473017,01/03/2017,9869,5812,type1,810,2017-03-30,350.0,POS,0,0.00,-1,30,3,2017,3,0,12.0,5.861,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False

-----------------------------------------

#### __9__. (2 points за правильную итоговую подтаблицу)

Сохраните итоговую подтаблицу в файл.

In [93]:
df.iloc[index].to_csv('answer.csv', index=False, sep=',')

-----------------------------------------

## Бонусная часть (+3 балла)

Попробуйте придумать решающее правило (без использования алгоритмов машинного обучения), по которому можно было бы предсказать значение переменной `target_flag`. **Запрещается** использовать переменную `target_sum`.

Разобъем выборку на тренировочную и отложенную.

In [ ]:
from sklearn.model_selection import train_test_split

mask = df.columns.str.startswith('target_')

target_cols  = df.columns[mask]
feature_cols = df.columns[~mask]

X, y = df.loc[:, feature_cols], df.loc[:, target_cols]

X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, shuffle=True, random_state=9872)

Ваше решение должно побить следующий бейзлайн:

```python
from sklearn.metrics import accuracy_score

assert accuracy_score(y_test['target_flag'], y_pred) > 0.7
```

**Запрещается** использовать отложенную выборку `(X_test, y_test)` для выбора решения.

**Вопрос:** Что показывает метрика `accuracy`?

$\textcolor{red}{Ваш \ ответ:}$

### Вопросы и подсказки

Исследуйте рапределения и зависимости между признаками отностительно целевой переменной `target_flag`. Для решения этой задачи вам может быть полезна визуализация.

1. Какие любопытные выводы можно сделать из такого анализа?
2. Какие проблемы возникают с визуализацией совместного распредления категориальных (дискретных) и непрерывных значений? Как эту проблему можно решить?
3. В исходном датасете очень много записей, поэтому визуализация может работать **неприемлемо** долго. Как решить эту проблему?

Приведите ниже код и комментарии с ответами на вопросы выше.

__Ответы на вопросы:__

**1.** _put your answers here_

**2.**  _put your answers here_

**3.** _put your answers here_

In [ ]:
# put your code here

### Решение

In [ ]:
#############################
### ╰( ͡° ͜ʖ ͡° )つ──────☆*:・ﾟ
#############################

In [ ]:
accuracy_score(y_test['target_flag'], y_pred)

0.7309009608981067